// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZwx3KpIkynY8SEew5aCibLZC-VoAH2E',
    appId: '1:850601885112:web:647be6313b7b5fc940634d',
    messagingSenderId: '850601885112',
    projectId: 'auth-conneciton',
    authDomain: 'auth-conneciton.firebaseapp.com',
    storageBucket: 'auth-conneciton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcduTEqd95dCgxTI_qBpkOF-c71fwC6zA',
    appId: '1:850601885112:android:2eb904fefc98a08440634d',
    messagingSenderId: '850601885112',
    projectId: 'auth-conneciton',
    storageBucket: 'auth-conneciton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vwmDUc_8TLyszsLgwO5DzhqCIj1Q1Gw',
    appId: '1:850601885112:ios:102894a9aff686b340634d',
    messagingSenderId: '850601885112',
    projectId: 'auth-conneciton',
    storageBucket: 'auth-conneciton.appspot.com',
    iosClientId: '850601885112-728uacub6pl2o6nlvpjrbddnsg85jrkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vwmDUc_8TLyszsLgwO5DzhqCIj1Q1Gw',
    appId: '1:850601885112:ios:102894a9aff686b340634d',
    messagingSenderId: '850601885112',
    projectId: 'auth-conneciton',
    storageBucket: 'auth-conneciton.appspot.com',
    iosClientId: '850601885112-728uacub6pl2o6nlvpjrbddnsg85jrkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthConnection',
  );
}
